name: Exécuter un script Python périodiquement

on:
  push:
    branches: [main, master]
  schedule:
    - cron: '0 3 * * *'  
  workflow_dispatch: 

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    container: inseefrlab/onyxia-vscode-python:py3.12.7

    steps:
      - name: Checkout du dépôt
        run: git clone https://github.com/InseeFrLab/DoReMIFaSol-bot.git |
                cd DoReMIFaSol-bot

      - name: Exécution du script Python
        run: python generer_json.py
        env:
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
